goals:
  dock_test:
    goal_list: ['home', 'pick', 'place']

    home: {frame_id: 'map', position: [1.225, 0.608, 0.000], orientation: [0.001, -0.000, -0.750, 0.662]}
    pick: {frame_id: 'map', position: [0.546, -0.132, -0.000], orientation: [0.000, -0.002, -0.739, 0.673]}
    place: {frame_id: 'map', position: [1.812, -0.335, -0.000], orientation: [-0.003, -0.002, -0.739, 0.674]}
